# Generated by Django 3.2.25 on 2024-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240409_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_token',
            field=models.CharField(max_length=100),
        ),
    ]
