# Generated by Django 3.2.25 on 2024-04-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usersession_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
