# Generated by Django 3.2.25 on 2024-04-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usersession_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='is_active',
        ),
    ]
