# Generated by Django 3.2.25 on 2024-04-09 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_usersession_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='session_token',
            new_name='token',
        ),
    ]
